python2 main.py ecu911 Archivo 1 WSCatalogos
python2 main.py saei SolicitudCorreo 0 WSSaei
python2 main.py saei TipoCamara 0 WSSaei
python2 main.py ecu911 Proveedor 1 WSPersonas
python2 main.py ecu911 Person 1 WSPersonas
python2 main.py ecu911 Functionary 1 WSPersonas
python2 main.py saei Provincia 0 WSSaei
python2 main.py ecu911 Provincia 1 WSCatalogos
python2 main.py ecu911 GroupDetails 1 WSCatalogos
python2 main.py ecu911 Position 1 WSCatalogos
